export const BASE_URL = process.env.REACT_APP_BASE_URL;

export const SET_ACTIVE = "SET_ACTIVE";
export const SET_SPIN = "SET_SPIN"

export const maxAgeCookie = 86400;


export const SET_SKIP = "SET_SKIP";
export const SET_TAKE = "SET_TAKE";
export const SET_ROWS = "SET_ROWS";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";

export const SET_CAFE_DETAIL = "SET_CAFE_DETAIL";
export const SET_CAFE_DETAIL_ERROR = "SET_CAFE_DETAIL_ERROR";
export const UPDATE_CAFE_SUCCESS = "UPDATE_CAFE_SUCCESS";
export const UPDATE_CAFE_ERROR ="UPDATE_CAFE_ERROR";
export const GET_CAFE_LIST_ERROR = "GET_CAFE_LIST_ERROR";
export const GET_CAFE_LIST_SUCCESS = "GET_CAFE_LIST_SUCCESS";

export const SET_EMPLOYEE_DETAIL = "SET_EMPLOYEE_DETAIL";
export const SET_EMPLOYEE_DETAIL_ERROR = "SET_EMPLOYEE_DETAIL_ERROR";
export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
export const UPDATE_EMPLOYEE_ERROR ="UPDATE_EMPLOYEE_ERROR";
export const GET_EMPLOYEE_LIST_ERROR = "GET_EMPLOYEE_LIST_ERROR";
export const GET_EMPLOYEE_LIST_SUCCESS = "GET_EMPLOYEE_LIST_SUCCESS";